### ISSUE TITLE
文献和目录问题

### ISSUE THREAD

**Issue by TownsW** [xiamenwcy/LaTeXFileforXMUThesis#1]
学长好，感谢您的分享，模板很好用。不过使用过程中还有一点点问题希望得到您的解答呀，方便的话希望留个联系方式谢谢！
具体问题为：
1.目录问题：英文目录缺点点点。
2.文献问题：INPROCEEDINGS类型的文献显示出来总是多几个逗号点之类的。
这里似乎不能上传图片，我把截图放在百度云盘上，求回复呀。（图片链接：https://pan.baidu.com/s/1jrMjSMdP5ZbMZUB2eQ_8jA 
提取码：lq9d ）

**Comment by xiamenwcy** [comment]
你好，欢迎你使用我的模板。你说的问题我们那时毕业交论文没有顾虑这些问题。当然，我现在已经毕业很久了，所以这些问题还是希望你们能查资料解决。我这里提供的只能是个参考。
